[package]
name = "runtime_docs_gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "runtime_docs_gen"
path = "main.rs"

[dependencies]
deno_doc = "0.95.0"
deno_graph = "0.63.5"
deno_ast = "0.32.1"
anyhow = { version = "1.0.79" }
futures = "0.3.30"
indexmap = "2.1.0"
